models:
  - name: low
    provider: openai
    model: google/gemini-2.5-flash-lite
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

  - name: medium
    provider: openai
    model: deepseek/deepseek-chat-v3-0324
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

  - name: high
    provider: openai
    model: anthropic/claude-3.5-sonnet
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

  - name: ultra
    provider: openai
    model: anthropic/claude-opus-4
    apiBase: https://openrouter.ai/api/v1
    apiKey: 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

defaultModel: medium